### ISSUE TITLE
How can I tag new data in stl to vtp format?

### ISSUE THREAD

**Issue by FPerezHernandez92** [Alsheghri/Teeth-Segmentation#1]
Thank you for the work. How could I label new data in stl format to get the vtp with which the network is trained?

**Comment by FarnooshGhadiri** [comment]
Hi FPerezHernande ..to test..you can read your mesh by             mesh = Easy_Mesh(os.path.join(data_path, file_name)) which Easy_mesh is a class in easy_mesh_vtk.py...so to read the file..you do not need to change it to VTP..but if you need vtp format you can first read your mesh using Easy_Mesh  and save it as vtp by mesh.to_vtp...

**Comment by FPerezHernandez92** [comment]
Thank you very much for your response. What I need is to label new examples. I have them in stl format but I have no problem converting them to vtp. How can I label these new examples? 

I know the ParaView program but I don't know how to label it. I don't know if you have used Vedo to label your data.

**Comment by FarnooshGhadiri** [comment]
You can use MeshLabeler by tai (https://github.com/Tai-Hsien/Mesh_Labeler) .

**Comment by FPerezHernandez92** [comment]
Thank you very much, that's what I needed.
